baseURL = "https://matjaz.it/"
canonifyURLs = true ## Transform all URLs to absolute using baseURL
copyright = "Creative Commons Attribution 4.0 International License"
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = false # does not put default language into /en, but in /
disableLanguageSwitchingButton=true
editor = "e"
enableEmoji = false
enableRobotsTXT = true
languageCode = "en-US"
log = true
logFile = "hugo.log"
metaDataFormat = "toml"
title = "Thinking in a digital life"
verbose = true
verboseLog = true

[Languages]
    [Languages.en]
        weight = 1
[author]
    name = "Matjaž Guštin"
    email = "blog@matjaz.it"
[permalinks]
    post = "/:slug/"
    page = "/:slug/"
[taxonomies]
    category = "categories"
    tag = "tags"
[sitemap]
    changefreq = "weekly"
    priority = 0.5
[params]
    logo      = "/images/logos/matjaz_it_logo.png"
    logohr    = "/images/logos/matjaz_it_logo@2x.png"
    twitter   = "https://twitter.com/TheMatjaz"
    handle    = "@TheMatjaz"
    github    = "https://github.com/TheMatjaz"
    email     = "blog@matjaz.it"
    keybase   = "https://keybase.io/TheMatjaz"
    cc        = "<a rel='license' href='https://creativecommons.org/licenses/by/4.0/'>CC BY 4.0 license</a>"
    keywords    = "Matjaž, Guštin, Matjaz, Gustin, blog, software, sysadmin, database, security, privacy, unix, linux, clean, code, development, hugo"
    description = "Software development, privacy and system administration"
    licenseURL  = "/legal-notice/"
    stylesheetURL = "/css/style.min.css"
    highlightJSURL = "/css/highlight.pack.js"
